baseURL = 'https://sakibsnaz.vercel.app/'
languageCode = 'en-us'
title = 'sakibsNaz/>'
theme = 'digitalgarden'

googleAnalytics = "UA-PROPERTY_ID"

[menu]
[[menu.main]]
name = 'ğŸ‘¤ Home'
url = '/'
weight = 1
[[menu.main]]
name = 'Content'
params.header = true
weight = 2
[[menu.main]]
name = 'ğŸ“œ Articles'
url = '/articles'
weight = 3
[[menu.main]]
name = 'ğŸ’» Experience'
url = '/experience'
weight = 4
[[menu.main]]
name = 'ğŸ’¼ Projects'
url = '/projects'
weight = 5
[[menu.main]]
name = 'ğŸ› ï¸ Stack'
url = '/stack'
weight = 6
[[menu.main]]
name = 'ğŸ§¾ Certificates'
url = '/certificates'
weight = 7
[[menu.main]]
name = 'Profiles'
params.header = true
weight = 8
[[menu.main]]
name = 'ğŸŒ WordPress'
url = 'https://profiles.wordpress.org/sakibsnaz/'
weight = 9
[[menu.main]]
name = 'â­ Fiverr'
url = 'https://www.fiverr.com/sakibsnaz'
weight = 10
[[menu.main]]
name = 'Blogs'
params.header = true
weight = 11
[[menu.main]]
name = 'ğŸ–Šï¸ dev.to'
url = 'https://dev.to/dashboard'
weight = 12
[[menu.main]]
name = 'ğŸ«±ğŸ»â€ğŸ«²ğŸ½ medium'
url = 'https://medium.com/@nazsakib'
weight = 13
[[menu.main]]
name = 'Others'
params.header = true
weight = 14
[[menu.main]]
name = 'ğŸ“š Reading List'
url = '/reading_list'
weight = 15
[[menu.main]]
name = 'ğŸ¬ Watchlist'
url = '/watchlist'
weight = 16

[[menu.social]]
name = 'Twitter'
url = 'https://twitter.com/sakibsnaz'
weight = 1
[[menu.social]]
name = 'GitHub'
url = 'https://github.com/nazsakib'
weight = 2
[[menu.social]]
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/sakibsnaz/'
weight = 3
[[menu.social]]
name = 'Gmail'
url = 'mailto:sakibsnaz@gmail.com'
weight = 4

# syntax highlight settings
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true
