baseURL = 'https://sakibsnaz.com/'
languageCode = 'en-us'
title = 'sakibsNaz/>'
theme = 'digitalgarden'

[menu]
[[menu.main]]
name = 'ğŸ‘¤ Home'
url = '/'
weight = 10
[[menu.main]]
name = 'Content'
params.header = true
weight = 20
[[menu.main]]
name = 'ğŸ“œ Articles'
url = '/articles'
weight = 30
[[menu.main]]
name = 'ğŸ’» Experience'
url = '/experience'
weight = 40
[[menu.main]]
name = 'ğŸ’¼ Projects'
url = '/projects'
weight = 50
[[menu.main]]
name = 'ğŸ› ï¸ Stack'
url = '/stack'
weight = 60
[[menu.main]]
name = 'ğŸ‘¨ğŸ¾â€ğŸ”§ Services'
url = '/services'
weight = 70
[[menu.main]]
name = 'ğŸ§¾ Certificates'
url = '/certificates'
weight = 80
[[menu.main]]
name = 'Profiles'
params.header = true
weight = 90
[[menu.main]]
name = 'ğŸŒ WordPress'
url = 'https://profiles.wordpress.org/sakibsnaz/'
weight = 100
[[menu.main]]
name = 'Blogs'
params.header = true
weight = 110
[[menu.main]]
name = 'ğŸ–Šï¸ dev.to'
url = 'https://dev.to/dashboard'
weight = 120
[[menu.main]]
name = 'ğŸ«±ğŸ»â€ğŸ«²ğŸ½ medium'
url = 'https://medium.com/@nazsakib'
weight = 130
[[menu.main]]
name = 'Others'
params.header = true
weight = 140
[[menu.main]]
name = 'ğŸ“š Reading List'
url = '/reading_list'
weight = 150
[[menu.main]]
name = 'ğŸ¬ Watchlist'
url = '/watchlist'
weight = 160

[[menu.social]]
name = 'Twitter'
url = 'https://twitter.com/sakibsnaz'
weight = 1
[[menu.social]]
name = 'GitHub'
url = 'https://github.com/nazsakib'
weight = 2
[[menu.social]]
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/sakibsnaz/'
weight = 3
[[menu.social]]
name = 'Gmail'
url = 'mailto:sakibsnaz@gmail.com'
weight = 4
[[menu.social]]
name = 'Youtube'
url = 'https://www.youtube.com/@sakibsnaz'
weight = 5


# syntax highlight settings
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true
